### ISSUE TITLE
Add missing pieces to make:user

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#133]
- Ask for auto generated id yes/no + type name. See https://medium.com/@jacekbulowski.kontakt/hi-i-tried-it-several-times-and-it-fails-every-single-time-10a387b0bb64

- Generate console context element factory. See https://medium.com/@tomsgu/thanks-for-your-work-roland-b5423dab35e1

**Comment by Tomsgu** [comment]
About the second issue from [here](https://medium.com/@tomsgu/thanks-for-your-work-roland-b5423dab35e1). These are the steps to reproduce it.

```bash
$ bin/console user:change-credential

 Username:
 > peter

 Select a field to change:
  [0] nickname
  [1] password
 > 1

 Select a field to change:
  [0] nickname
  [1] password
 > 0

 Select a field to change:
  [0] nickname
  [1] password
 > 1

 Select a field to change:
  [0] nickname
  [1] password
 > 
```
The problem can be on [this](https://github.com/msgphp/msgphp/blob/master/src/User/Infra/Console/Command/ChangeUserCredentialCommand.php#L74) line when passing null, instead of asking for a new credential before.

When passing password as argument, everything is good.
```bash
$ bin/console user:change-credential --password=passwd

 Username:
 > peter
                                                                                                                        
 [OK] Changed user credential for peter                                                                                  
                                                                                                                        
      > Field "password" changed from "passwds" to "passwd"         
```
