### ISSUE TITLE
Default string for logged in user

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#327]
I'm not sure how to create a default string for the app.user variable in Twig

                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <a href="{{ path('logout') }}">Logout {{ app.user }}</a>
                {% endif %}

I added a __toString() method to my User.php class, but that didn't change anything.

```php
    <!-- src/Entity/User.php -->
    public function __toString()
    {
        return $this->getCredential()->getUsername();
    }
```

If I use app.user.username, I get the user id, but the string I want is the nickname, and I'd prefer to define the string in the PHP, and not specify that in the twig file.

**Comment by ro0NL** [comment]
Hi @tacman 

Using `app.user` returns the Symfony security user (`UserInterface`), that's a DTO implemented by 

- (0.10): https://github.com/msgphp/msgphp/blob/v0.10.0/src/User/Infrastructure/Security/SecurityUser.php
- (0.11/master): https://github.com/msgphp/msgphp/blob/master/src/User/Infrastructure/Security/UserIdentity.php

From the user identity you mihgt want to obtain `app.user.originUsername`.

If you want the entity model (e.g. `App\Entity\User`) then use `msgphp_user.current` instead.

See  also the demo implementation: https://github.com/msgphp/symfony-demo-app/blob/2ab7dee77aa721297066bdaf78e5afe2e3845a3b/templates/base.html.twig#L15-L20

`msgphp_user.current.email` ultimately exists because of https://github.com/msgphp/msgphp/blob/82899c2ae3688230719ca7ebbda1112b4ea176b2/src/User/Model/EmailCredential.php#L27-L30 but this depends on your own User modeling.

`User::getCredential()->getUsername()` always works consistently (if you dont know it's e..g `getEmail` vs. `getNickname`). But the explicit API should always be preferred.

**Comment by ro0NL** [comment]
More info about these 2 layers: https://stovepipe.systems/post/decoupling-your-security-user
